# Generated by Django 3.1.3 on 2020-11-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuCao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, null=True)),
                ('text', models.CharField(max_length=1024, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
