# Generated by Django 3.1.3 on 2020-11-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('href', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
