# Generated by Django 3.1.3 on 2020-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0002_homehref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=1024, null=True)),
                ('user', models.CharField(max_length=16, null=True)),
                ('other_user', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
