# Generated by Django 3.1.3 on 2020-11-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0003_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeHref',
            new_name='DB_HomeHref',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='DB_Project',
        ),
        migrations.RenameModel(
            old_name='TuCao',
            new_name='DB_TuCao',
        ),
    ]
