# Generated by Django 3.1.3 on 2020-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0004_auto_20201110_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_id', models.CharField(max_length=10, null=True)),
                ('api_name', models.CharField(max_length=100, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('api_header', models.CharField(max_length=1000, null=True)),
                ('api_host', models.CharField(max_length=100, null=True)),
                ('api_login', models.CharField(max_length=10, null=True)),
                ('des', models.CharField(max_length=1000, null=True)),
                ('body_code', models.CharField(max_length=20, null=True)),
                ('api_body', models.CharField(max_length=1000, null=True)),
                ('result', models.TextField(null=True)),
                ('sign', models.CharField(max_length=10, null=True)),
                ('file_key', models.CharField(max_length=50, null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('public_header', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='db_project',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='db_project',
            name='remark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
