# Generated by Django 3.1.3 on 2020-11-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0005_auto_20201111_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_apis',
            old_name='prj_id',
            new_name='api_id',
        ),
    ]
