# Generated by Django 3.1.3 on 2020-11-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestOne', '0006_auto_20201111_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_apis',
            old_name='api_id',
            new_name='prj_id',
        ),
    ]
